### ISSUE TITLE
Mail notifications

### ISSUE THREAD

**Issue by Remo** [ortic/concrete5-forum#2]
One should have to ability to receive an email when a new message is posted to a topic.
There needs to be a checkbox so that one can opt-out from receiving messages when posting a topic or message. There also needs to be a button so that one can receive notifications without posting anything.

**Comment by rosie607** [comment]
I'm not getting any email notifications, am I missing a setting somewhere or is there an issue?
I have just added the Forum package to a fresh install of C5 8.4.4

<img width="1215" alt="screenshot 2019-02-01 at 16 27 49" src="https://user-images.githubusercontent.com/11563269/52135810-8f914180-263e-11e9-8049-7548739c8873.png">

**Comment by Remo** [comment]
that's hard to tell, are other concrete5 emails being sent?

**Comment by rosie607** [comment]
The Forgot password email works...

**Comment by Remo** [comment]
In that case I would have to debug the code..

**Comment by rosie607** [comment]
My apologies, the issue is with the 'from' email address in the concrete config file.
I noticed that some emails from C5 come from concrete5-noreply@concrete5 (not the Forgot password though)
I have changed the email address to no-reply@mydomain.com and it works fine.

[(https://www.concrete5.org/community/forums/customizing_c5/email-not-working-in-8.1)]
