### ISSUE TITLE
Handling when user is deleted

### ISSUE THREAD

**Issue by Remo** [ortic/concrete5-forum#7]
We have a few ways to handle deleted users

* Keep the message and show "deleted user" instead of avatar and username
* Delete the message, but that would cause a gap in the discussion.
* Keep the message record, but show "deleted message" and "deleted user" to indicate that there used to be a message

**Comment by fagansystems** [comment]
HI, I quite like the route taken by some systems that allow the owned messages to be re-assigned on delete to another user, so, for example, you could have a user 'hidden' with a '?' explaining what it means

like the effort so far keep it up.

**Comment by Remo** [comment]
Not sure that's feasible, the problem caused by GDPR means that users delete their account at random times after which we'll have to decide what to do. It's not something the admin does, if a user deletes his account I would want to cleanup everything.

I think I'll just remove the user id from the message and display "delete user". You could still overwrite the element and change this to "hidden" if that suits your needs.

Still have to find the time to work on this package though ;-)

**Comment by fagansystems** [comment]
ah yes that's a good point so showing 'deleted user' is the best compromise. Can users delete the content when they delete their account? That would cause gaps in the threads

**Comment by Remo** [comment]
I don't know enough about GDPR, I'd very much like to keep the message, if that's allowed.

**Comment by fagansystems** [comment]
Same here, I did a few web searches and came up with this as a question 'How will the term “Personal Data” be defined within the GDPR?' From what I have read GDPR is related to Personal data, my guess and it would need someone with more time and a clearer knowledge of this regulation, is that if the personal data is removed/deleted, in this case the account then what is left may be ok, I say maybe because what if the messages are tagged with a personal name. The websites I found explore this in more detail. It defines the data of interest as personal data, Everything else is fair game

**Comment by Remo** [comment]
To me public information isn't that personal, otherwise you wouldn't have shared it with the world, but I'm no lawyer. I'd appreciate feedback from anyone with more knowledge than I have!

**Comment by fagansystems** [comment]
I would be interested in that as well

**Comment by Remo** [comment]
I'm going to close this. From what I understand it should be fine as long as we explain things properly in the terms and conditions you might want to show the user when the register, but please don't take my word for it. If there's anyone with more knowledge, let me know.
